num1 = int(input("first value: "))
num2 = int(input("second value: "))
print(num1 + num2)
print(num1 - num2)
print(num1 * num2)
print(num1 / num2)
print(num1 // num2)
print(num1 % num2)
print(num1 ** num2)
print(min(num1, num2))